###
### A complete description of a Prefect Deployment for flow 'hello-flow'
###
name: my-flow-deploy
description: null
version: cbbc6d3714285d6ed42a8f09a1ad3e3f
# The work queue that will handle this deployment's runs
work_queue_name: default
tags:
- test
parameters: {}
schedule: null
infra_overrides: {}
infrastructure:
  type: kubernetes-job
  env:
    - name: PREFECT_ORION_API_HOST
      value: localhost
  labels: {}
  name: null
  command: null
  image: prefecthq/prefect:2.6.9-python3.7
  namespace: prefect
  service_account_name: null
  image_pull_policy: null
  cluster_config: null
  job:
    apiVersion: batch/v1
    kind: Job
    metadata:
      labels: {}
    spec:
      template:
        spec:
          parallelism: 1
          completions: 1
          restartPolicy: Never
          containers:
          - name: prefect-job
            env: []
  customizations: []
  job_watch_timeout_seconds: 5
  pod_watch_timeout_seconds: 60
  stream_output: true
  finished_job_ttl: null
  block_type_slug: kubernetes-job
  _block_type_slug: kubernetes-job

###
### DO NOT EDIT BELOW THIS LINE
###
flow_name: hello-flow
manifest_path: null
storage: null
path: /opt/prefect/flows
entrypoint: main.py:hello_flow
parameter_openapi_schema:
  title: Parameters
  type: object
  properties:
    name_input:
      title: name_input
  required:
  - name_input
  definitions: null
